version: '3.8'

networks:
  send_email_network:
    driver: bridge
  microservices_network:
    external: true

volumes:

services:
  # =================================================================
  # SEND EMAIL SERVICE
  # =================================================================

  send_email_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${SEND_EMAIL_IMAGE_NAME}
    container_name: ${SEND_EMAIL_CONTAINER_NAME}
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - send_email_network
      - microservices_network
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - CACHE_DRIVER=${CACHE_DRIVER}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}

  send_email_webserver:
    image: nginx:alpine
    container_name: ${SEND_EMAIL_WEBSERVER_NAME}
    restart: unless-stopped
    ports:
      - "${SEND_EMAIL_PORT}:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - send_email_network
    depends_on:
      - send_email_app

  # =================================================================
  # INFRASTRUCTURE SERVICES
  # =================================================================

  mailpit:
    image: axllent/mailpit:latest
    container_name: ${MAILPIT_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${MAILPIT_WEB_PORT}:8025"
      - "${MAILPIT_SMTP_PORT}:1025"
    networks:
      - send_email_network
      - microservices_network
